#!/bin/bash

# Check the Operating System to get the default environment file
if [ "$(uname)" == "Darwin" ]; then
    envFile=$HOME/.bash_profile
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    envFile=$HOME/.bashrc
fi

dailybinPath=`pwd`

# Check if installed before
if grep -q "#####  Add by Daily Bin ###########" "$envFile"; then
    # Install Before was found
    echo 'Dailybin has been installed on your system.'
    exit -1
fi

# Modify the envFile
echo >> $envFile
echo "###################################" >> $envFile
echo "#####  Add by Daily Bin ###########" >> $envFile
echo "############################Start>>>" >> $envFile
echo export PATH="\"${dailybinPath}/bin:\$PATH\"" >> $envFile
echo "#############################<<<End" >> $envFile

# Source to update environment.
echo "Dailybin installed successfully."
echo "Restart your Terminal to make effect."
