#!/bin/bash

# Get the default shell
defaultShell=$SHELL

# Check the Operating System to get the default environment file
if [ "$(uname)" == "Darwin" ]; then
    if [[ $defaultShell == *"bash"* ]]; then
        envFile=$HOME/.bash_profile
    elif [[ $defaultShell == *"zsh"* ]]; then
	envFile=$HOME/.zshrc
    fi
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    if [[ $defaultShell == *"bash"* ]]; then
        envFile=$HOME/.bashrc
    elif [[ $defaultShell == *"zsh"* ]]; then
	envFile=$HOME/.zshrc
    fi
fi

dailybinPath=`pwd`

# Check if installed before
if grep -q "# DailyBin" "$envFile"; then
    # Install Before was found
    echo 'Dailybin has been installed on your system.'
    exit -1
fi

# Modify the envFile
echo >> $envFile
echo "###################################" >> $envFile
echo "# DailyBin" >> $envFile
echo "############################Start>>>" >> $envFile
echo export PATH="\"${dailybinPath}/bin:\$PATH\"" >> $envFile
#echo for file in \$\(find "${dailybinPath}" -type f -o -type d\)\; do >> $envFile
#echo '    export PATH="$file:$PATH"
#done' >> $envFile

## Add 'open' tool to open folder from Linux Command
if [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    echo "alias open=\"xdg-open\"" >> $envFile
fi

echo "#############################<<<End" >> $envFile

# Show Tip to source environment file.
echo "Dailybin installed successfully."
echo "Restart the terminal to take effect."
